// <auto-generated />
namespace CSharpEgtim_301_OOP.DataAccsessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mg1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mg1));
        
        string IMigrationMetadata.Id
        {
            get { return "202505162017549_mg1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
